### ISSUE TITLE
Use PHP to include server.php, not HTML script tag

### ISSUE THREAD

**Issue by machawk1** [CatLover91/WebDevCourse#2]
I noticed on https://github.com/CatLover91/WebDevCourse/blob/master/index.php#L89 that you pulled in the initialization script using an HTML script tag. The browser does not like this, as it expects the content at the URI you specified to be JavaScript, which it is not -- it's PHP + HTML.

Instead of 

``` html
<div class="row">
  <script type="text/javascript" src="server.php"></script>
</div>
```

Use PHP's [include_once](http://php.net/manual/en/function.include-once.php) functionality, e.g.,

``` php
<div class="row">
<?php
  include_once "server.php";
?>
</div>
```

This was the source of your HTML form not appearing.

**Comment by n3k0lai** [comment]
I have implemented this change, I will test functionality of it tonight.

**Comment by n3k0lai** [comment]
This change has been implemented correctly. I am marking this issue as closed.
