### ISSUE TITLE
convert inline sql to a dump

### ISSUE THREAD

**Issue by n3k0lai** [CatLover91/WebDevCourse#7]

**Comment by machawk1** [comment]
:thumbsup: This will make the code much more maintainable, as we discussed.

**Comment by n3k0lai** [comment]
Inline dump of proposed SQL database configuration has been added by commit e59c5360d08df9945d14573e357cc1c1a93c4824. 

I am keeping this issue open, as I still need to add dummy data into the dump.

**Comment by n3k0lai** [comment]
This is complete, I am marking it as resolved.
